#! /bin/sh

DOCKER_COMPOSE_FILE="$HOME/nipro/nephroflow-api/docker-compose.yml"
CONTAINER_NAME="nephroflow_web"

INTERACTIVE=false

while getopts 'i:' FLAG; do
    case "$FLAG" in
        i) INTERACTIVE=true;;
    esac
done


CONTAINER_ID="$(docker ps -q -f name=$CONTAINER_NAME -f status=running)"

if [ ! $CONTAINER_ID ]; then
  docker-compose -f $DOCKER_COMPOSE_FILE run --service-ports -d web
fi

CONTAINER_ID="$(docker ps -q -f name=$CONTAINER_NAME -f status=running)"

if [ $INTERACTIVE = true ]; then
  # docker exec -it $CONTAINER_ID $2
  if [ -t 1 ] ; then
    docker exec -it $CONTAINER_ID $2;
  else
    docker exec -i $CONTAINER_ID $2;
  fi
else
  docker exec $CONTAINER_ID $1
fi
